<?php

include("conexion.php");
$con=conectar();

$NID_ARTICULO=$_POST['NID_ARTICULO'];
$CNOMBRE_ARTICULO=$_POST['CNOMBRE_ARTICULO'];
$CDESCRIPCION_ARTICULO=$_POST['CDESCRIPCION_ARTICULO'];
$NID_AUTOR=$_POST['NID_AUTOR'];
$NID_RAMA_CONOCIMIENTO=$_POST['NID_RAMA_CONOCIMIENTO'];
$DFECHA_PUBLICACION=$_POST['DFECHA_PUBLICACION'];
$NID_REVISTA=$_POST['NID_REVISTA'];

$sql="UPDATE TBL_ARTICULO  SET  NID_ARTICULO='$NID_ARTICULO',CNOMBRE_ARTICULO='$CNOMBRE_ARTICULO',CDESCRIPCION_ARTICULO='$CDESCRIPCION_ARTICULO',NID_AUTOR='$NID_AUTOR',NID_RAMA_CONOCIMIENTO='$NID_RAMA_CONOCIMIENTO',DFECHA_PUBLICACION='$DFECHA_PUBLICACION',NID_REVISTA='$NID_REVISTA' WHERE NID_ARTICULO='$NID_ARTICULO'";
$query=mysqli_query($con,$sql);

    if($query){
        Header("Location: articulo.php");
    }
?>