<?php

include("conexion.php");
$con=conectar();

$NID_AUTOR=$_POST['NID_AUTOR'];
$CNOMBRE_REAL=$_POST['CNOMBRE_REAL'];
$CNOMBRE_ARTISTICO=$_POST['CNOMBRE_ARTISTICO'];
$CCORREOELECTRONICO=$_POST['CCORREOELECTRONICO'];

$sql="UPDATE TBL_AUTOR  SET  NID_AUTOR='$NID_AUTOR',CNOMBRE_REAL='$CNOMBRE_REAL',CNOMBRE_ARTISTICO='$CNOMBRE_ARTISTICO',CCORREO_ELECTRONICO='$CCORREO_ELECTRONICO' WHERE NID_AUTOR='$NID_AUTOR'";
$query=mysqli_query($con,$sql);

    if($query){
        Header("Location: autor.php");
    }
?>